name: Deploy Laravel + React to cPanel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and build React
        run: |
          npm install
          npm run build

      - name: Deploy React build to root
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          source: "public/build/*"
          target: "/home/${{ secrets.CPANEL_USERNAME }}/public_html"
          

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, pdo_mysql
          tools: composer

      - name: Install Laravel dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Deploy Laravel app
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          source: "./*"
          target: "/home/${{ secrets.CPANEL_USERNAME }}/public_html/personal_portfolio"
          strip_components: 0
          rm: true
          exclude: |
            node_modules/
            .github/
            .git/
            .env
            .vscode/
            tests/
           

      - name: Final server setup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          script: |
            cd /home/${{ secrets.CPANEL_USERNAME }}/public_html/personal_portfolio
            
            # Environment setup
            [ -f .env ] || cp .env.example .env
            php artisan key:generate
            
            # Permissions
            chmod -R 755 storage
            chmod -R 755 bootstrap/cache
            
            # Cache optimizations
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            # Run migrations
            php artisan migrate --force