name: Deploy Laravel & React to cPanel

on:
  push:
    branches:
      - main  # Change to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies & Build React
        run: |
          npm install
          npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2  # Adjust based on your Laravel setup
          extensions: mbstring, bcmath, pdo, pdo_mysql
          tools: composer

      - name: Install Laravel Dependencies
        run: |
          composer install --no-dev --prefer-dist
          php artisan config:cache
          php artisan route:cache

      - name: Deploy via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          source: "./backend/*, ./frontend/build/*"
          target: "/home/your_cpanel_user/public_html"

      - name: Run Migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          script: |
            cd /home/your_cpanel_user/public_html
            php artisan migrate --force